### ISSUE TITLE
Mongodb cluster Docker Unable to connect from other machine to Docker host machine (Centos 7)

### ISSUE THREAD

**Issue by sinalkar** [senssei/mongo-cluster-docker#13]
Hi,

This code working like charm on local machine, but i unable to connect to from my other machine. 
(Local Machine and Host Machine on Same network)

I tried to connect from command line using following command

`mongo --host testreplica/192.168.24.5:30001,192.168.24.5:30002,192.168.24.5:30003 test_db -u test_user -p testpassword`

Its shows something like,

> ongoDB shell version v3.4.13
> connecting to: mongodb://192.168.24.5:30001,192.168.24.5:30002,192.168.24.5:30003/test_db?replicaSet=testreplica
> 2018-04-26T13:09:41.521+0530 I NETWORK  [thread1] Starting new replica set monitor for testreplica/192.168.24.5:30001,192.168.24.5:30002,192.168.24.5:30003
> 2018-04-26T13:09:41.524+0530 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to 192.168.24.5:30001 (1 connections now open to 192.168.24.5:30001 with a 5 second timeout)
> 2018-04-26T13:09:41.524+0530 I NETWORK  [thread1] Successfully connected to 192.168.24.5:30002 (1 connections now open to 192.168.24.5:30002with a 5 second timeout)
> 2018-04-26T13:09:41.525+0530 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] changing hosts to testreplica/172.19.0.2:27017,172.19.0.3:27017,172.19.0.4:27017 from testreplica/192.168.24.5:30001,192.168.24.5:30002,192.168.24.5:30003
> 2018-04-26T13:09:44.531+0530 W NETWORK  [thread1] Failed to connect to 172.19.0.4:27017, in(checking socket for error after poll), reason: No route to host
> 2018-04-26T13:09:44.531+0530 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Failed to connect to 172.19.0.3:27017, in(checking socket for error after poll), reason: No route to host
> 2018-04-26T13:09:47.537+0530 W NETWORK  [thread1] Failed to connect to 172.19.0.2:27017, in(checking socket for error after poll), reason: No route to host
> 2018-04-26T13:09:51.043+0530 W NETWORK  [thread1] Failed to connect to 172.19.0.4:27017, in(checking socket for error after poll), reason: No route to host
> 2018-04-26T13:09:54.049+0530 W NETWORK  [thread1] Failed to connect to 172.19.0.2:27017, in(checking socket for error after poll), reason: No route to host
> 2018-04-26T13:09:57.055+0530 W NETWORK  [thread1] Failed to connect to 172.19.0.3:27017, in(checking socket for error after poll), reason: No route to host
> 2018-04-26T13:09:57.055+0530 W NETWORK  [thread1] No primary detected for set testreplica
> 2018-04-26T13:09:57.055+0530 I NETWORK  [thread1] All nodes for set testreplica are down. This has happened for 1 checks in a row.
> 2018-04-26T13:09:57.055+0530 E QUERY    [thread1] Error: connect failed to replica set testreplica/192.168.24.5:30001,192.168.24.5:30002,192.168.24.5:30003 :
> connect@src/mongo/shell/mongo.js:240:13
> @(connect):1:6
> exception: connect failed

Also i tried this option from
https://docs.docker.com/network/bridge/#enable-forwarding-from-docker-containers-to-the-outside-world

$ sysctl net.ipv4.conf.all.forwarding=1

sudo iptables -P FORWARD ACCEPT

**Comment by senssei** [comment]
You will probably need user define bridge/ host only network to achieve that, depending on configuration of your network.

I would start with this piece of documentation https://blog.docker.com/2016/12/understanding-docker-networking-drivers-use-cases/ and 

```bash
sudo docker network ls
```
to determine ids of configuration of bridge and host network

```bash
sudo docker network inspect <your id>
```
to confirm network configuration. Then you can reconfigure / create new it accordingly and then update my docker-compose.

https://docs.docker.com/compose/networking/#configure-the-default-network 

BTW What operating system and docker version ?

**Comment by sinalkar** [comment]
Thanks for quick response
following is my docker-compose file

```
version: '2'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo:3.4.14
        ports:
            - "30002:27017"
        volumes:
            - ./mongodb.key:/data/mongodb.key
            - /mnt/mongo-data-2:/data/db/
            - /etc/localtime:/etc/localtime:ro 
        command: mongod  --replSet testreplica  --rest --httpinterface --port 27017 --oplogSize 16 --smallfiles
        restart: always
        networks:
        - mongodb-network 
    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo:3.4.14
        ports:
            - "30003:27017"
        volumes:
            - ./mongodb.key:/data/mongodb.key  
            - /mnt/mongo-data-3:/data/db/
            - /etc/localtime:/etc/localtime:ro   
        command: mongod  --replSet testreplica  --rest --httpinterface --port 27017 --oplogSize 16 --smallfiles
        restart: always 
        networks:
        - mongodb-network 
    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo:3.4.14
        ports:
            - "30001:27017"
        volumes:
            - ./mongodb.key:/data/mongodb.key 
            - /mnt/mongo-data-1:/data/db/ 
            - /etc/localtime:/etc/localtime:ro   
        command: mongod  --replSet testreplica  --rest --httpinterface --port 27017 --oplogSize 16 --smallfiles
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always
        networks:
        - mongodb-network 
    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:3.4.14
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        volumes:
            - ./scripts:/scripts 
            - ./mongodb.key:/data/mongodb.key
            - /mnt/mongo-data-setup:/data/db/ 
            - /etc/localtime:/etc/localtime:ro 
        env_file:
        - ./.env
        networks:
        - mongodb-network          
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=testreplica
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
networks:
    mongodb-network:
      driver: bridge

```
Yes i use User Define bridge network only

> [
>     {
>         "Name": "project_testprod_mongodb-network",
>         "Id": "417fe3379bed74b29707b8671b350021ce11305217b602d2e09d60c17e40e2b4",
>         "Created": "2018-04-20T16:36:08.325559369+05:30",
>         "Scope": "local",
>         "Driver": "bridge",
>         "EnableIPv6": false,
>         "IPAM": {
>             "Driver": "default",
>             "Options": null,
>             "Config": [
>                 {
>                     "Subnet": "172.19.0.0/16",
>                     "Gateway": "172.19.0.1"
>                 }
>             ]
>         },
>         "Internal": false,
>         "Attachable": false,
>         "Ingress": false,
>         "ConfigFrom": {
>             "Network": ""
>         },
>         "ConfigOnly": false,
>         "Containers": {
>             "433ba4e1bf5d1ec03769a6281263a3f776e9760a00d502e679cbb25497552446": {
>                 "Name": "mongo-cnf-3",
>                 "EndpointID": "87581398921f1aeecae3ca828a1ada34d95b868475aad19d3cad41b2d21a933b",
>                 "MacAddress": "02:42:ac:13:00:02",
>                 "IPv4Address": "172.19.0.2/16",
>                 "IPv6Address": ""
>             },
>             "5f565964391abd1ecbee317135ac770378fb7ade0d0dc27cb89d6ac214ecc438": {
>                 "Name": "mongo-cnf-1",
>                 "EndpointID": "83f92afa5e6af23dd4243da355354c059cf1891fa4e589fe05b9215c6598b57c",
>                 "MacAddress": "02:42:ac:13:00:04",
>                 "IPv4Address": "172.19.0.4/16",
>                 "IPv6Address": ""
>             },
>             "f46ddc963727e53d556bf1ec1c0529a7acb07b60cec10405549066d818e56591": {
>                 "Name": "mongo-cnf-2",
>                 "EndpointID": "b25394139a9238fecd4148c5932571912589d7d4a74c6845484feea86d5364f6",
>                 "MacAddress": "02:42:ac:13:00:03",
>                 "IPv4Address": "172.19.0.3/16",
>                 "IPv6Address": ""
>             }
>         },
>         "Options": {},
>         "Labels": {}
>     }
> ]
> 

**BTW What operating system and docker version ?**
OS : Centos 7 x64bit

> Docker Version : 
> Client:
>  Version:       18.04.0-ce
>  API version:   1.37
>  Go version:    go1.9.4
>  Git commit:    3d479c0
>  Built: Tue Apr 10 18:21:36 2018
>  OS/Arch:       linux/amd64
>  Experimental:  false
>  Orchestrator:  swarm
> 
> Server:
>  Engine:
>   Version:      18.04.0-ce
>   API version:  1.37 (minimum version 1.12)
>   Go version:   go1.9.4
>   Git commit:   3d479c0
>   Built:        Tue Apr 10 18:25:25 2018
>   OS/Arch:      linux/amd64
>   Experimental: false
>
