### ISSUE TITLE
I have a bit of a problem.

### ISSUE THREAD

**Issue by hello4leaf** [senssei/mongo-cluster-docker#9]
I have a bit of a problem.
I use your code, and I have used three replicas, so I have a problem that I do not understand.

> ERROR: Service 'mongo-router' depends on service 'mongo-rs3-setup' which is undefined.

**Create additional files. "docker-compose.3.yml"**
```
version: '2'
services:
    mongo-3-2:
        container_name: "mongo-3-2"
        image: mongo
        ports:
            - "30032:27017"
        command: mongod --replSet rs3 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-3-3:
        container_name: "mongo-3-3"
        image: mongo
        ports:
            - "30033:27017"
        command: mongod --replSet rs3 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-3-1:
        container_name: "mongo-3-1"
        image: mongo
        ports:
            - "30031:27017"
        command: mongod --replSet rs3 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-3-2:mongo-3-2
            - mongo-3-3:mongo-3-3
        restart: always

    mongo-rs3-setup:
        container_name: "mongo-rs3-setup"
        image: mongo
        depends_on:
            - "mongo-3-1"
            - "mongo-3-2"
            - "mongo-3-3"
        links:
            - mongo-3-1:mongo-3-1
            - mongo-3-2:mongo-3-2
            - mongo-3-3:mongo-3-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-3-1
            - MONGO2=mongo-3-2
            - MONGO3=mongo-3-3
            - RS=rs3
        entrypoint: [ "/scripts/setup.sh" ]

```

**Modify files. "docker-compose.shard.yml" (ports and depends_on, links,environment)**
```
version: '2'
services:
    mongo-router:
        container_name: "mongo-router"
        image: mongo
        ports:
            - "37031:27017"
        depends_on:
            - "mongo-rs1-setup"
            - "mongo-rs2-setup"
            - "mongo-rs3-setup"
            - "mongo-cnf-setup"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
            - mongo-3-1:mongo-3-1
            - mongo-3-2:mongo-3-2
            - mongo-3-3:mongo-3-3
        command: mongos --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017
        restart: always

    mongo-shard-setup:
        container_name: "mongo-shard-setup"
        image: mongo
        depends_on:
            - "mongo-router"
        links:
            - mongo-router:mongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=mongo-router
            - MONGO11=mongo-1-1
            - MONGO12=mongo-1-2
            - MONGO13=mongo-1-3
            - MONGO21=mongo-2-1
            - MONGO22=mongo-2-2
            - MONGO23=mongo-2-3
            - MONGO31=mongo-3-1
            - MONGO32=mongo-3-2
            - MONGO33=mongo-3-3
            - RS1=rs1
            - RS2=rs2
            - RS3=rs3
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init-shard.sh" ]
        restart: on-failure:20

```

And...
Modify init-shard.sh file
```
#!/bin/bash 

mongodb1=`ping -c 1 ${MONGOS} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`

mongodb11=`ping -c 1 ${MONGO11} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`
mongodb12=`ping -c 1 ${MONGO12} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`
mongodb13=`ping -c 1 ${MONGO13} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`

mongodb21=`ping -c 1 ${MONGO21} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`
mongodb22=`ping -c 1 ${MONGO22} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`
mongodb23=`ping -c 1 ${MONGO23} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`

mongodb31=`ping -c 1 ${MONGO31} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`
mongodb32=`ping -c 1 ${MONGO32} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`
mongodb33=`ping -c 1 ${MONGO33} | head -1  | cut -d "(" -f 2 | cut -d ")" -f 1`

port=${PORT:-27017}

echo "Waiting for startup.."
until mongo --host ${mongodb1}:${port} --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
  printf '.'
  sleep 1
done

echo "Started.."

echo init-shard.sh time now: `date +"%T" `
mongo --host ${mongodb1}:${port} <<EOF
   sh.addShard( "${RS1}/${mongodb11}:${PORT1},${mongodb12}:${PORT2},${mongodb13}:${PORT3}" );
   sh.addShard( "${RS2}/${mongodb21}:${PORT1},${mongodb22}:${PORT2},${mongodb23}:${PORT3}" );
   sh.addShard( "${RS3}/${mongodb31}:${PORT1},${mongodb32}:${PORT2},${mongodb33}:${PORT3}" );
   sh.status();
EOF

```

And....
Execution proceeded in the following order.
```
docker-compose -f docker-compose.1.yml up -d
docker-compose -f docker-compose.2.yml up -d
docker-compose -f docker-compose.3.yml up -d
docker-compose -f docker-compose.cnf.yml up -d
docker-compose -f docker-compose.shard.yml up -d
```

The container is also running well (maybe ..)
**docker ps -a**
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
fc2fdca63f7c        mongo               "/scripts/setup-cn..."   15 minutes ago      Up 15 minutes       27017/tcp                  mongo-cnf-setup
456ad9a0d02c        mongo               "docker-entrypoint..."   15 minutes ago      Up 15 minutes       0.0.0.0:30001->27017/tcp   mongo-cnf-1
40f02b4b73e5        mongo               "docker-entrypoint..."   15 minutes ago      Up 15 minutes       0.0.0.0:30003->27017/tcp   mongo-cnf-3
61211e609ea1        mongo               "docker-entrypoint..."   15 minutes ago      Up 15 minutes       0.0.0.0:30002->27017/tcp   mongo-cnf-2
1da83345cf14        mongo               "/scripts/setup.sh"      16 minutes ago      Up 16 minutes       27017/tcp                  mongo-rs3-setup
50504749f187        mongo               "docker-entrypoint..."   16 minutes ago      Up 16 minutes       0.0.0.0:30031->27017/tcp   mongo-3-1
7517e293bf64        mongo               "docker-entrypoint..."   16 minutes ago      Up 16 minutes       0.0.0.0:30033->27017/tcp   mongo-3-3
99a0241d44d0        mongo               "docker-entrypoint..."   16 minutes ago      Up 16 minutes       0.0.0.0:30032->27017/tcp   mongo-3-2
5eb4f41e9cc0        mongo               "/scripts/setup.sh"      17 minutes ago      Up 17 minutes       27017/tcp                  mongo-rs2-setup
9e4a739f8dbc        mongo               "docker-entrypoint..."   17 minutes ago      Up 17 minutes       0.0.0.0:30021->27017/tcp   mongo-2-1
fe570b7269bc        mongo               "docker-entrypoint..."   17 minutes ago      Up 17 minutes       0.0.0.0:30022->27017/tcp   mongo-2-2
20b2412a1b78        mongo               "docker-entrypoint..."   17 minutes ago      Up 17 minutes       0.0.0.0:30023->27017/tcp   mongo-2-3
783fadb516c9        mongo               "/scripts/setup.sh"      19 minutes ago      Up 19 minutes       27017/tcp                  mongo-rs1-setup
46a5fca17104        mongo               "docker-entrypoint..."   19 minutes ago      Up 19 minutes       0.0.0.0:30011->27017/tcp   mongo-1-1
1949685b824a        mongo               "docker-entrypoint..."   19 minutes ago      Up 19 minutes       0.0.0.0:30013->27017/tcp   mongo-1-3
9597d0035946        mongo               "docker-entrypoint..."   19 minutes ago      Up 19 minutes       0.0.0.0:30012->27017/tcp   mongo-1-2
```
